// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scqdpqogynspbcanlzmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjcWRwcW9neW5zcGJjYW5sem10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDc4NjEsImV4cCI6MjA2MzEyMzg2MX0.pZbiJohcMXXfhb__efVcN8u80ct9-TjlkDSX4aJSXt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);